package com.books.services;

import com.books.model.Book;
import com.books.utils.Utils;
import org.junit.Assert;

import java.util.Map;

public class CreateBookActions extends BaseService {

    protected static final String CREATE_BOOK_PATH = "/api/v1/books";
    public Book bookData;
    public Map<String, Object> invalidBookData;

    public void setBookData(Book book) {
        this.bookData = book;
    }

    public void setInvalidBookData(Map<String, Object> data) {
        this.invalidBookData = data;
    }

    public void createBook() {
        executePostRequest(CREATE_BOOK_PATH, bookData);
    }

    public void createBookWithInvalidData() {
        executePostRequest(CREATE_BOOK_PATH, invalidBookData);
    }


    public void createBookWithEmptyBody() {
        executePostRequest(CREATE_BOOK_PATH, "");
    }

    public void createBookWithMalformedJson() {
        String malformedJson = "{ \"name\": \"Test Book\", \"author\": \"Test Author\", \"publication\": \"Test Pub\", \"category\": \"Test Cat\", \"pages\": \"invalid\", \"price\": }";
        executePostRequest(CREATE_BOOK_PATH, malformedJson);
    }


    public void validateBookIdIsAutoGenerated() {
        Integer bookId = response.jsonPath().get("id");
        Assert.assertNotNull("Book ID should be auto-generated and not null", bookId);
        Assert.assertTrue("Book ID should be a positive integer", bookId > 0);
    }

    public void validateCreatedBookDataMatchesInput() {
        Utils.validateBookDataMatchesInput(response, bookData);
    }

    public Integer getBookIdFromResponse() {
        return response.jsonPath().get("id");
    }
}
