name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn clean test
      
    - name: List target directory contents
      run: |
        echo "Contents of target directory:"
        ls -la target/ || echo "target directory does not exist"
        echo "Contents of allure-results directory:"
        ls -la target/allure-results/ || echo "allure-results directory does not exist"
        
    - name: Generate Allure results
      run: |
        # Create allure-results directory if it doesn't exist
        mkdir -p target/allure-results
        # Generate Allure results from test execution
        mvn allure:report -Dallure.results.directory=target/allure-results
        
    - name: List allure-results after generation
      run: |
        echo "Contents of allure-results directory after generation:"
        ls -la target/allure-results/ || echo "allure-results directory still does not exist"
        
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: target/allure-results
        if-no-files-found: warn
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports
        if-no-files-found: warn

  allure-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Download Allure Results
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: allure-results
        path: target/allure-results
        
    - name: Check if Allure results exist
      run: |
        if [ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ]; then
          echo "Allure results found"
          ls -la target/allure-results/
        else
          echo "No Allure results found, creating empty directory"
          mkdir -p target/allure-results
          echo "{}" > target/allure-results/empty-result.json
        fi
        
    - name: Generate Allure Report
      run: |
        mvn allure:report
        
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: target/site/allure-maven-plugin
        if-no-files-found: warn
        
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/site/allure-maven-plugin
        destination_dir: allure-reports